---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: repo.startreedata.io/external-docker-registry/ci-java-17
    tag: latest

inputs:
- name: ci-src
- name: src

caches: 
- path: src/m2

outputs:
- name: release-version
- name: release-notes

params:
  GIT_BRANCH: 
  GIT_PRIVATE_KEY: ((git.ssh-private-key))
  GIT_URI:  
  GIT_USER_EMAIL: 
  GIT_USER_NAME: "Concourse PaaSaS Bot"

run:
  path: ci-src/.concourse/tasks/release/release.sh