---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: paasas/ci
    tag: latest

inputs:
- name: ci-src
- name: src
- name: repository

outputs:
- name: image

caches: 
- path: src/m2

params:
  GIT_BRANCH:
  GIT_REPOSITORY_BRANCH:  repository 
  GIT_PRIVATE_KEY: ((git.ssh-private-key))
  GIT_URI: 
  GIT_USER_EMAIL: 
  GIT_USER_NAME: "Concourse PaaSaS Bot"

run:
  path: ci-src/.concourse/tasks/publish/publish.sh