resource_types:

resources:
- name: ci-src
  type: git
  source: 
    uri: git@github.com:paas-moe-le-cloud/teleport-java-client.git
    private_key: ((git.ssh-private-key))
    branch: main
    paths:
    - .concourse

- name: src
  type: git
  source: 
    uri: git@github.com:paas-moe-le-cloud/teleport-java-client.git
    private_key: ((git.ssh-private-key))
    branch: main
    ignore_paths:
    - .concourse
    - helm

- name: repository
  type: git
  source: 
    uri: git@github.com:paas-moe-le-cloud/teleport-java-client.git
    private_key: ((git.ssh-private-key))
    branch: repository
    ignore_paths:
    - .concourse
    - helm

jobs:
- name: publish-main
  plan:
  - in_parallel:
    - get: src
      trigger: true
    - get: ci-src
    - get: repository
  - task: publish-main
    privileged: true
    file: ci-src/.concourse/tasks/publish/publish.yml
    params:
      GIT_BRANCH: main
      GIT_URI: git@github.com:paas-moe-le-cloud/teleport-java-client.git
      GIT_USER_EMAIL: admin+concourse-paasas@daniellavoie.dev

- name: release-main
  plan:
  - in_parallel:
    - get: src
      passed: ["publish-main"]
    - get: ci-src
  - task: release
    privileged: true
    file: ci-src/.concourse/tasks/release/release.yml
    params:
      GIT_BRANCH: main
      GIT_URI: git@github.com:paas-moe-le-cloud/teleport-java-client.git
      GIT_USER_EMAIL: admin+concourse-paasas@daniellavoie.dev

display:
  background_image: https://64.media.tumblr.com/d5cc2ecd26a4d02a840d5a91f515c318/tumblr_n04563a3vR1qj86bro1_500.gifv